config/routes.rb
Rails.application.routes.draw do
  root to: "home#show"

  delete '/logout', to: 'sessions#destroy'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'

  resources :users, only: [:new, :create] do
    resources :links, only: [:index, :create, :update, :edit]
  end

  namespace :api do
    namespace :v1 do
      resources :links, only: [:update]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :user
  validates :url, presence: true
  validates :url, url: true
  validates :title, presence: true

  def status
    self.read ? "Mark as Unread" : "Mark as Read"
  end

  def type
    self.read ? "read" : "unread"
  end
end

app/models/scraper.rb
require 'nokogiri'
require 'open-uri'

class Scraper
  attr_reader :url, :data

  def initialize(url)
    @url = url
  end

  def data
    @data ||= Nokogiri::HTML(open(url))
  end

  def header
    head = data.at_css "h1"
    head.text
  end

  def title
    title = data.at_css "title"
    title.text
  end

  def paragraph
    para = data.at_css "p"
    para.text
  end

  def summary
    h1 = data.at_css "h1"

    h1 ? header : paragraph
  end

  def message
    "Visit #{self.title} and enjoy!  #{self.summary}"
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :links
  validates :email, presence: true, uniqueness: true
end

app/controllers/api/v1/links_controller.rb
class Api::V1::LinksController < ApplicationController
  def update
    link = Link.find(params[:id])
    if link.read
      link.update(read: false)
    else
      link.update(read: true)
    end
    link.save
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  def index
    @links = current_user.links.order(id: :desc)
    @link = Link.new
  end

  def create
    @link = Link.new(user_id: current_user.id, title: link_params[:title], url: link_params[:url])
    @user = User.find(params[:user_id])
    if @link.save
      flash[:success] = "Link Created!!"
      redirect_to user_links_path(current_user)
    else
      redirect_to user_links_path(current_user)
      flash[:danger] = "Invalid URL."
    end
  end

  def edit
    @link = Link.find(params[:id])
  end

  def update
    @link = Link.find(params[:id])

    if @link.update_attributes(link_params)
      redirect_to user_links_path(current_user)
      flash[:success] = "Link Updated!"
    else
      flash[:danger] = "Invalid URL."
      render :edit
    end
  end

  private

  def link_params
    params.require(:link).permit(:title, :url)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id

      redirect_to user_links_path(current_user)
    else
      flash.now[:danger] = "Invalid login"
      render :new
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id

      redirect_to user_links_path(@user)
    else
      flash.now[:error] = @user.errors.full_messages.join(", ")
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/show.html.erb
<main>
  <h1 class="welcome">Welcome to URLockBox!</h1>
  <h4 class="instructions">Please Sign Up or Log In</h4>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>URLockbox</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
</head>

<body>
  <% flash.each do |type, message| %>
  <%= content_tag :div, sanitize(message), class: "alert alert-#{type}" %>
  <% end %>
  <% if current_user %>
  <%= link_to "Logout", logout_path, method: :delete, class: "btn btn-danger logout" %>
  <% else %>
  <%= link_to "Log In", login_path, class: "btn btn-primary log-in" %>
  <%= link_to "Sign Up", new_user_path, class: "btn btn-primary sign-up"   %>
  <% end %>

  <%= yield %>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>

app/views/links/edit.html.erb
<div class="container center">
  <h2>Edit Link</h2>
  <div class="row">
    <%= form_for [current_user, @link] do |f| %>
    <%= f.text_field :title, placeholder: "Title" %>
    <br><br>
    <%= f.text_field :url, placeholder: "URL" %>
    <br><br>
    <%= f.submit "Submit", class: "btn btn-primary btn-sm", method: :put %>
    <% end %><br>
  </div>
</div>

app/views/links/index.html.erb
<div class="container center">
  <div class="row header">
    <h1>Enter New Link</h1>
    <%= form_for [current_user, @link] do |f| %>
    <%= f.text_field :title, placeholder: "Title" %>
    <br><br>
    <%= f.text_field :url, placeholder: "URL" %>
    <br><br>
    <%= f.submit "Submit", class: "btn btn-primary btn-sm", method: :post %>
    <% end %>
    <h2>All Links</h2>
  </div>
  <div class="row center-table">
    <input id="typed" placeholder="Search by title or url">
    <button type="button" name="button" class="sort-alpha btn btn-primary btn-sm">Sort Alphabetically</button>
    <button type="button" name="button" class="filter-read btn btn-primary btn-sm">Filter Read</button>
    <button type="button" name="button" class="filter-unread btn btn-primary btn-sm">Filter Unread</button>
    <table id="linkTable">
      <thead>
        <tr>
          <th>Title</th>
          <th>URL</th>
          <th>Status</th>
          <th>Modify Status</th>
          <th>Edit Link</th>
        </tr>
      </thead>
      <tbody id="searchBody">
        <% @links.each do |link| %>
        <tr class="<%= link.type %>" data-link-id="<%= link.id %>">
          <td><%= link_to "#{link.title}", link.url %></td>
          <td>
            <%= link_to "#{link.url}", link.url %><br>
            <% @scraper = Scraper.new(link.url) %>
            <b><%= @scraper.title %></b><br>
            <%= @scraper.message %>
          </td>
          <td><%= link.type %></td>
          <td><button type="button" name="button" class="toggle btn btn-primary btn-sm"> <%= link.status %> </button></td>
          <td> <%= link_to "Edit Link", edit_user_link_path(current_user, link), class: "btn btn-primary btn-sm" %> </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/new.html.erb
<div class="container center">
  <h1>Sign Up</h1>
<%= form_for [@user] do |f| %>
<%= f.text_field :email, placeholder: "Email" %>
<br><br>
<%= f.password_field :password, placeholder: "Password" %>
<br><br>
<%= f.password_field :password_confirmation, placeholder: "Password Confirmation" %>
<br><br>
<%= f.submit "Submit", class: "btn btn-primary btn-sm" %>
<% end %>
</div>